### ISSUE TITLE
dual_quat muliplication

### ISSUE THREAD

**Issue by GostInShell** [alirezaahmadi/Dual-Quaternions#1]
Hi! Thank you for contributing such a neat and clear impementation of Dual Quaternion operations in cuda. It has been really helpful to me.

Yet I notice a little problem in dual_quat muliplication at [here](https://github.com/alirezaahmadi/Dual-Quaternions/blob/fee68d3e193f7c81a9d2319ef21395d01715fa31/math_dualQuat.h#L167C70-L167C70). I believe the dual part of the multiplication should be `(real* q.dual) + (dual * q.real)`.

**Comment by alirezaahmadi** [comment]
thanks for contributing and committing the change
